# Generated by Django 3.0.4 on 2020-03-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='user', max_length=264)),
                ('lname', models.CharField(default='user', max_length=264)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
